language: php
php:
#  - '5.4'
#  - '5.5'
#  - '5.6'
  - '7.0'
#  - hhvm

install:
  - composer install
  #coveralls needs this dir.
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover xml/clover.xml

after_success:
  - php vendor/bin/coveralls --coverage_clover=xml/clover.xml
